cache:
  paths:
    - ${CI_PROJECT_DIR}/.cache/pip

.poetry.template:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  before_script:
    - pip install poetry
  
stages:
  - build
  - docker
  - Kuber

build:
  extends: .poetry.template
  stage: build
  script:
    - poetry build
    
  artifacts:
    paths:
      - "dist/*"
      
docker:
  stage: docker
  tags:
    - docker-runner
  script:
    - echo "Docker is running!"

Deploy:
  stage: Kuber
  script:
    - echo "This job deploys something!"
   