image: docker:latest

services:
  - docker:dind

#variables:
#  DOCKER_DRIVER: overlay2
#  DOCKER_TLS_CERTDIR: ""
#  GIT_SSL_NO_VERIFY: "1"

cache:
  paths:
    - .m2/repository/
    - target/

.poetry.template:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  before_script:
    - pip install poetry
  
stages:
  - build
  - docker
  - Kuber

build:
  extends: .poetry.template
  stage: build
  script:
    - poetry build
    
  artifacts:
    paths:
      - "dist/*"
      
docker:
  stage: docker
  #when: manual
  tags:
    - docker-runner
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile.build . -t $CONTAINER_TAGGED_IMAGE
    - docker push $CONTAINER_TAGGED_IMAGE
  artifacts:
    paths:
      - target/*.jar


Deploy:
  stage: Kuber
  script:
    - echo "This job deploys something!"
   