image: maven:latest

stages:
  - build
  - docker
  - Kuber

build:
  stage: build
  script:
  - mvn spring-boot:run
    
docker:
  stage: docker
  tags:
    - docker-runner
  script:
    - echo "Docker is running!"

Deploy:
  stage: Kuber
  script:
    - echo "This job deploys something!"
   