image: docker:latest
services:
  - docker:dind

stages:
  - build
  - docker
  - kuber

variables:
  VARIABLE_DATA: Gitlab-CI-YAML
  ENV: "test"


.kuber: &kuber
  script:
    - export REGISTRY_BASIC=$(echo -n ${CI_DEPLOY_USER}:${CI_DEPLOY_PASSWORD} | base64)
    #- cat ./deploy/namespace.yaml | envsubst | kubectl apply -f -
    - kubectl apply -f ./deploy/namespace.yaml
    - kubectl get ns
    - cat ./deploy/secret.yaml | envsubst | kubectl apply -f -
    - cat ./deploy/deployment.yaml | envsubst | kubectl apply -f -
    - cat ./deploy/service.yaml | envsubst | kubectl apply -f -

build:
  stage: build
  script:
    echo "St1"

docker:
  stage: docker
  image: docker
  services:
    - docker:18-dind
  script:
    - apk update && apk add jq
    - export VERSION=`jq -r ".version" < ./package.json`
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    
deploy_oda2-vip:
  image: thisiskj/kubectl-envsubst
  stage: kuber
  variables:
    REPLICAS: 1
    SERVER: "https://oda2-vip.magnum.local:6443"
    CA_CERT: $CERT_ODA
    SA_TOKEN: $DEPLOY_SA_TOKEN_ODA
    DEPLOY_SA_NAME: "gitlab"
  before_script:
    - echo "$CA_CERT" > /oda2ca.crt
    - kubectl config set-cluster k8s --server=$SERVER
    - kubectl config set clusters.k8s.certificate-authority /oda2ca.crt
    - kubectl config set-credentials $DEPLOY_SA_NAME --token=$SA_TOKEN
    #- kubectl config set-context $ENV --cluster=k8s --user=$DEPLOY_SA_NAME --namespace=${CI_PROJECT_NAME}-${ENV}
    - kubectl config set-context $ENV --cluster=k8s --user=$DEPLOY_SA_NAME --namespace=test 
    - ping oda2-vip.magnum.local
    - kubectl config use-context $ENV
    - kubectl config get-contexts
    - kubectl get nodes -o wide
  when: manual
  environment:
    name: ${ENV}
  only:
    - master
  tags:
    - prod-runner
  <<: *kuber
  
deploy_kuber:
  image: thisiskj/kubectl-envsubst
  stage: kuber
  variables:
    REPLICAS: 1
    SERVER: "https://172.16.8.136:6443"
    CA_CERT: $CERT_ODA
    SA_TOKEN: $DEPLOY_SA_TOKEN_ODA
    DEPLOY_SA_NAME: "gitlab"
  before_script:
    - cat /etc/hosts
    - echo '172.16.8.136 test-kuat-centos.magnum.local test-kuat-centos' >> /etc/hosts
    - cat /etc/hosts
    - ping test-kuat-centos
    - echo "$CA_CERT" > /oda2ca.crt
    - echo "$CA_CERT"
    - kubectl config set-cluster k8s --server=$SERVER
    - kubectl config set clusters.k8s.certificate-authority /oda2ca.crt
    - kubectl config set-credentials $DEPLOY_SA_NAME --token=$SA_TOKEN
    - kubectl config set-context $ENV --cluster=k8s --user=$DEPLOY_SA_NAME --namespace=${CI_PROJECT_NAME}-${ENV}
    - kubectl config use-context $ENV
    - kubectl config get-contexts
    - kubectl get nodes -o wide
  when: manual
  environment:
    name: ${ENV}
  only:
    - master
  tags:
    - docker-runner
  <<: *kuber
 