stages:
  - build
  - docker
  - deploy

build:
  stage: build
  script:
    - echo "Hello world!"
    
docker:
  stage: docker
  script:
    - echo "Docker is running!"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something!"
   