cache:
  paths:
    - ${CI_PROJECT_DIR}/.cache/pip

.poetry.template:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  before_script:
    - pip install poetry
  
stages:
  - build
  - docker
  - Kuber

build:
  extends: .poetry.template
  stage: build
  script:
    - poetry build
    
  artifacts:
    paths:
      - "dist/*"
      
docker:
  runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
  stage: docker
  tags:
    - docker-runner

Deploy:
  stage: Kuber
  script:
    - echo "This job deploys something!"
   