apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlabpdt
stringData:
  .dockerconfigjson: '{"auths":{"${CI_REGISTRY}":{"username":"${CI_DEPLOY_USER}","password":"${CI_DEPLOY_PASSWORD}","email":"${CI_DEPLOY_USER}@magnum.kz","auth":"${REGISTRY_BASIC}"}}}'
