apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: git
stringData:
  .dockerconfigjson: '{"auths":{"${CI_REGISTRY}":{"username":"${CI_DEPLOY_USER}","password":"${CI_DEPLOY_PASSWORD}","email":"${CI_DEPLOY_USER}","auth":"${REGISTRY_BASIC}"}}}'
