apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: ${CI_PROJECT_NAME}
  name: ${CI_PROJECT_NAME}
spec:
  selector:
    app: ${CI_PROJECT_NAME}
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
