images: 
  - maven:latest
  - spring-boot:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APP_NAME: app-api
  
stages:
  - build
  - docker
  - Kuber

Package artifacts:
  stage: build
  image: openjdk:17-alpine
  only:
    - release
  script:
    - mvn $MAVEN_OPTS clean package
  artifacts:
    paths:
      - target/*.jar  
      
build:
  stage: build
  script:
  - mvn spring-boot:run
    
docker:
  stage: docker
  tags:
    - docker-runner
  script:
    - echo "Docker is running!"

Deploy:
  stage: Kuber
  script:
    - echo "This job deploys something!"
   